### ISSUE TITLE
manifest not found

### ISSUE THREAD

**Issue by xif4** [YourMJK/tum-live-recorder#1]
Trying to record a running stream results in not found
```
$ ./record.sh now
Recording starts on:  Di 28. Mai 10:08:35 CEST 2019


if (nr == 0 || nr == 1) { MMstartStream( document.getElementById("video1") , 'https://stream.lrz.de/livetum/MW2001COMB20190528083014544/manifest.m3u8: No such file or directory

⬤ Recording 'https://live.rbg.tum.de/cgi-bin/streams/MW2001/COMB' stream to './saved/2019-05-28.mp4'... (10:08:37)
(CRL-C to stop recording)



◼︎ Stopping recording... (10:08:37)
```

**Comment by YourMJK** [comment]
Sorry for not responding, seems like I didn't receive any email notifications…

This looks like it's an issue with the regex of the sed command in __getStreamURL.sh_.
For some reason `.*\'https` isn't getting matched properly on your system. Maybe it's an issue with the escaped single-quote…
What version of bash and sed (BSD?) are you using?

**Comment by Zerwin** [comment]
Not original OP, but had the same problem. Removing the single quote solved it.

**Comment by YourMJK** [comment]
The latest commit should have resolved this issue.
