### ISSUE TITLE
Two streams at once - Can't record the second one

### ISSUE THREAD

**Issue by SiKreuz** [YourMJK/tum-live-recorder#3]
I have two livestreams i want to record that are so close that they are overlapping a bit. When I want to record the second stream, it does record the end of the first stream and stops when this one is finished. So I cant really record the second stream.

**Comment by YourMJK** [comment]
Are those two lectures held in the same room?
If yes, then I'm aware of this issue and I'm pretty sure that reason for it is, that the stream of the first lecture stops _after_ the official start time of the second lecture.
That means that if you start the recording for the second lecture too early, it will still fetch the "old" URL for the previous stream.

Try setting up the second recording to start about 10 minutes later and see if that fixes the issue.

**Comment by SiKreuz** [comment]
Well, yes, those lectures are held in the same room. You have described it pretty well. That would fix the issue, but then there are the first 10 minutes missing of the second lecture. I just thought it would be great to add a feature that allows to select the second url for the second lecture if necessary.

**Comment by YourMJK** [comment]
Ah, I see. I will think of a way to implement this as an option nicely.
What day and time are these lectures being held at (so I can test it)?

**Comment by SiKreuz** [comment]
On wednesday, the first lecture is from 10am to 1pm (GDB) and the second one from 1pm to 2pm (GBS).

**Comment by SiKreuz** [comment]
I just recognized that the url contains the starting time of the lecture. Maybe you could use this information to receive the correct url. So if i want to record the lecture at 13:00, I just have to execute `./record.sh "<day> 13:00"` and it starts the record 5 minutes earlier with the url containing the "1300"-part. You may even offer an option for the lecture hall like `./record.sh <date> <hall>`. So you can generate the url directly.

**Comment by YourMJK** [comment]
That's a good idea. What I also tried was to add an argument to specify the "stream number" _n_ i.e. the _n_-th stream that is currently listed on the page.
That is what I tested today and it worked recording GBS with a stream number of 2.

But I think the best solution would be to parse the dates from the URLs of all current streams and select the one who's date is closest to the recording date (if there's more than one).
This way you won't have to specify the time precisely but it will still pick the correct stream.

I will try to implement this before next Wednesday and I'll think about the lecture hall option.

**Comment by rich-ayr** [comment]
If the numbers appended to MW0001 are timestamps just sorting the matches for `/cgi-bin/streams/MW.001.*/COMB` in descending order should do the trick.
Otherwise let's hope that the order of the streams are reliable. As a last resort fuzzy string search might be an option (not sure if there's a simple way to implement in bash).

**Comment by YourMJK** [comment]
For now, the recent commit should have fixed this issue (sorry I couldn't make it before today).
The script will now select the URL with most recent timestamp in the URL from the first two regex results.

However, with the default lecture hall regex, this current solution may introduce problems when you want to record the most recent stream in MW0001 but there is also a stream for MW2001 still running. I don't know if that case is possible to occur at the moment.
